### ISSUE TITLE
Hi, im the guy commented on modb. 

### ISSUE THREAD

**Issue by DOOMMARINE117** [DiccHead/DoomLauncher#1]
I still receive the issue. 

here is the pic of it. 

![20210917_124915](https://user-images.githubusercontent.com/64376960/133846434-aaac8480-1df1-477d-88c1-eb8939313561.jpg)

**Comment by DiccHead** [comment]
Now that I see it, i think it's because one of modules tries to access browser before knowing what browser to use. I will try to fix it in my free time.
(sorry if my english is bad)

**Comment by DOOMMARINE117** [comment]
i see. so its confuse.

no worries. english is a hard language to learn. i understand.

even i struggle.,

**Comment by DiccHead** [comment]
I googled and found out that the only way to fix it is to install chrome or chromium...
I will try to find more information about it and make it work without chrome/chromium if it's possible.
But if you want to use it now, i suggest you install chromium (it's very light weight). If you do it, you can use stable version from moddb.

**Comment by DOOMMARINE117** [comment]
im good for now. i can wait. no problem waiting.

**Comment by DiccHead** [comment]
I did some research and found out that there is no way to fix this issue, sorry...

**Comment by DOOMMARINE117** [comment]
unforunate. thanks thoguh.
